config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :people

  resources :sessions
  resources :signups, only: %i[new create]
  resources :password_reset_requests, only: %i[new create]
  resources :password_resets, only: %i[new create]

  get :settings, to: 'pages#settings'

  root to: "public/pages#index"

  draw :public

  mount GoodJob::Engine => 'good_job'
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id              :bigint           not null, primary key
#  email           :string
#  first_name      :string
#  last_name       :string
#  status          :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :bigint           not null
#
# Indexes
#
#  index_people_on_organization_id  (organization_id)
#
# Foreign Keys
#
#  fk_rails_...  (organization_id => organizations.id)
#
class Person < ApplicationRecord

  include OrganizationOwnable

  validates(:first_name, :last_name, presence: true)
  # validate :name_uniqueness

  has_many :contacts
  has_many :companies, through: :contacts

  def name_uniqueness
    people = Person.all.map{|e| [first_name, last_name].join(' ')}

    people.include?(full_name)

    errors.add(:base, 'Name must be unique.')
  end


  def full_name
    [first_name, last_name].join(" ")
  end
end

app/controllers/people_controller.rb
class PeopleController < AppController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to @person
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to @person
    else
      render :edit
    end
  end


  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :email)
  end
end

app/views/people/_form.slim
= form_with model: @person, path: @person, local: true, data: { action: 'turbo:submit-end->modal#close' } do |p|

  header
    h1 = @person.persisted? ? "Edit #{@person.first_name}" : 'New Person'
  .body
    = errors @person
    
    = panels do
      = panel name: 'Person', icon: :user do
        .grid
          .half
            = p.text_field :first_name
            = p.label :first_name
          .half
            = p.text_field :last_name
            = p.label :last_name
          .full
            = p.email_field :email
            = p.label :email
      = panel name: 'Memberships', icon: :building_estate do
        .checkboxes
          = p.collection_check_boxes :company_ids, Company.all, :id, :name do |b|
            .checkbox
              = b.check_box
              = b.label

  .footer
    .left.buttons
      = p.submit class: 'small primary'
      = modal_closer

app/views/people/_person.slim
= row class: 'person', id: dom_id(person) do
  = field body: person.full_name, label: 'Name'
  = field body: person.companies.count, label: 'memberships'
  = field class: 'options', label: 'Options' do
    = link_to person do
      = tabler_icon :eye
      span View

app/views/people/edit.html.slim
h1 People#edit
p Find me in app/views/people/edit.html.slim

app/views/people/index.html.slim
header.centered.flex.spaced.out
  h1 People
  .buttons
    = link_to "Create new person", [:new, :person], class: 'medium primary', data: { turbo_frame: 'modal' }

section.standout
  .body
    = table do
      = turbo_frame_tag :table do
        = render @people

app/views/people/new.html.slim
= turbo_frame_tag :modal do
  = content_tag :dialog, data: { controller: 'modal' } do
    = render 'form'

app/views/people/show.html.slim
h1 = @person.full_name