config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :people

  resources :sessions
  resources :signups, only: %i[new create]
  resources :password_reset_requests, only: %i[new create]
  resources :password_resets, only: %i[new create]

  get :settings, to: 'pages#settings'

  root to: "public/pages#index"

  draw :public

  mount GoodJob::Engine => 'good_job'
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id              :bigint           not null, primary key
#  name            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :bigint           not null
#
# Indexes
#
#  index_companies_on_organization_id  (organization_id)
#
# Foreign Keys
#
#  fk_rails_...  (organization_id => organizations.id)
#
class Company < ApplicationRecord
  include OrganizationOwnable

  # belongs_to :organization

  has_many :contacts
  has_many :people, through: :contacts

  has_many :proposals
  has_many :terms, through: :proposals

  validates(:name, presence: true, uniqueness: true)

end

app/controllers/companies_controller.rb
class CompaniesController < AppController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
    @people = @company.people
  end

  def new
    @company = Company.new
    @people = Person.all
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      render turbo_stream: [
        turbo_stream.prepend(:list, partial: 'companies/company', locals: { company: @company })
      ]
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
    @people = Person.all
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to @company
    else
      render :edit
    end
  end


  private

  def company_params
    params.require(:company).permit(:name, person_ids: [])
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.slim
= row class: 'company', id: dom_id(company) do
  = field body: company.name, label: 'Name'
  = field body: company.people.count, label: 'reps'
  = field class: 'options', label: 'Options' do
    = link_to company do
      = tabler_icon :eye
      span View

app/views/companies/_form.slim
= form_with model: @company, path: [@company], data: { action: 'turbo:submit-end->modal#close' } do |c|
  header
    h1 = @company.persisted? ? "Edit #{@company.name}" : 'New company'
  .body
    div
      = c.text_field :name
      = c.label :name

    h3 People
  
    .checkboxes
      = c.collection_check_boxes :person_ids, Person.all, :id, :full_name do |b|
        .checkbox
          = b.check_box
          = b.label

  .footer
    .left.buttons
      = c.submit class: 'small primary'
      = modal_closer

app/views/companies/edit.html.slim
h1 Edit #{@company.name}

= render 'form'

app/views/companies/index.html.slim
header.centered.flex.spaced.out
  h1 Companies
  .buttons
    = link_to "Create new company", new_company_path, class: 'medium primary', data: { turbo_frame: 'modal' }

section.standout
  .body
    = table do
      = turbo_frame_tag :list do
        = render @companies

app/views/companies/show.html.slim
h1 = link_to @company.name, [:edit, @company]

section
  h3 People
  ul
    = render @people



section
  h3 Proposals
  = link_to "New Proposal", [:new, @company, :proposal]
  ul
    = render @proposals